name: Deploy Branch

on:
  workflow_dispatch:
    branches:
      - 'master'
    inputs:
      version:
        required: true
        type: string
        description: Version for this release. Format "X.X.X".

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Create release branch
        uses: peterjgrainger/action-create-branch@v3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: version/${{ github.event.inputs.version }}


      - name: Create release in GitHub
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.inputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          commit: ${{ github.event.pull_request.head.sha }}
          body: ${{ github.event.head_commit.message }}